#!/bin/bash

#official name: ? CANTIO ? latin word for singing (birds); playing music

#front end some mpg321 control
runningfile="$HOME/.config/ty/musicty.pid"
runningout="$HOME/.config/ty/musicty.log"
volume_setting=10 #0-100
loop_num=0 #0 is infinite

#debugflag=''
debugflag="true"
forceflag=""
debug () { if [ -n "$debugflag" ]; then echo "$1"; fi; }

isDigit () {
	value="$1"
	#is not empty AND empty after removing all digits characters
	if [ -n "$value" -a -z "${value//[0-9]}" ]; then return 0
	else return 1; fi
}

playSong () {
	#play song in background
	mpg321 -g "$volume_setting" -l "$loop_num" "$1" &
	#store process of mpg321 in file
	echo -e "$!" > "$runningfile"
}

listSongChoice () {
	location="$HOME/Music/"
	choice=$(find "$location" -type f | fzf)
	printf "%s" "$choice"
}

randomSongChoice () {
	location="${1:-"$HOME/Music/nightmusic"}"
	tracklist=($(find "$location" -maxdepth 1 -type f))
	numtracks="${#tracklist[@]}"
    [ $numtracks -gt 0 ] && index=$(($RANDOM % $numtracks)) || exit 1
	printf "%s" "${tracklist[$index]}"

}

randomInfinite () {
	song="$(randomSongChoice)"
	debug "randomsongchoice: $song"
	playSong "$song"
}

# Call to try and stop any hung songs which are still playing. 
# Wipe anything like temp files, running processes, etc
shutdown () {
	id="$(cat $runningfile)"
	kill "$id"
	rm "$runningfile"
	exit 0
}

shutdownAll (){
	name='mpg321'
	if [ -z "$forceflag" ]; then
		echo "will kill all processes with the name: $name"
		echo "Proceed?? (y/n)"
		read -p '> ' choice
	else choice="y"
	fi
	if [ $choice = "y" ]; then pkill "$name"; rm "$runningfile"; fi
	
}

while [ -n "$1" ]; do
	#default mode is: pick random song and loop infinte times
	case "$1" in
		help|--help|-h)
			printf "%s\n" 'Functionality is super basic right now.'
			printf "%s\n" 'musicty inf		to loop one random song'
			printf "%s\n" 'musicty stop		to kill the launched process'
		;;
		--force|-f)
			forceflag="true"
		;;
		stop|quit|shutdown|reset|q|-q|--shutdown|--quit|--stop|-s)
			shutdown
		;;
		--stop-all|--force-stop|--force-quit)
			shutdownAll
		;;
		inf|--infinite|-inf|--inf|infinite)
			randomInfinite
		;;
		--choose|-c|--list|--list-songs)
			isDigit "$2" && { loop_num="$2"; shift; }
			song=$(listSongChoice)
			playSong "$song"
		;;
		--set-loops|--set-repeat|--loops|--repeat|-r)
			isDigit "$2" && { loop_num="$2"; shift; } #fails silently -- bad??
		;;
		interactive|--interactive|-i|i)
			echo "implement interactive mode please"
		;;
		*)
			echo ">$1< is not recognized input"
		;;
	esac
	shift
done

