#!/bin/bash

# '\033[x;ym <characters> \033[m'
# x=0 dark x=1 LIGHT
# y=color 30=black	34=blue		32=green	36=cyan
# 31=red	35=purple	33=brown	grey/white=37


# export PS1="\[\033[38;5;11m\]\u\[$(tput sgr0)\]@\h:\[$(tput sgr0)\]
# \[\033[38;5;6m\][\w]\[$(tput sgr0)\]: \[$(tput sgr0)\]"

# PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h
#\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '

output=''
exit_code="$?"

colorWord () {
	printf "%b" '\001\033['$1';'$2'm\002'
	printf "%s" "${3}"
	printf "%b" '\001\033[m\002'
}

setColor () {
	printf "%b" '\001\033['$1';'$2'm\002'
}
resetColor () {
	printf "%b" '\001\033[0m\002'
}
mailarca_module () {
	alerts=$(mailarca)
	if [ $alerts -gt 0 ]; then
		colorWord 0 36 "$alerts"
		colorWord 0 37 ':'
	fi
}
date_module () {
	colorWord 0 32 "$(date +%R)"
}

###########################################################################
while [ -n "$1" ]; do
	case $1 in
		--module|-m)
			if [ "$2" = "mailarca" ]; then mailarca_module; shift 2
			elif [ "$2" = "date" ]; then date_module; shift 2; fi
		;;
		*)
			shade=$(($RANDOM % 2)); color=$((($RANDOM % 7) + 30))
			colorWord $shade $color "$1"
			shift
		;;
	esac
done


