#!/bin/bash

#makes X of Y
if [ "$#" -le 0 ]; then printf "%s\n" "\
------------------   strbuilder <flags> <num> <elements>   ---------------------
USAGE: 	To create strings by repeating inputs to fill full length specified.
default example: strbuilder 12 str --> 'strstrstrstr'
  strbuilder --number/-n <num>		prints str of NUM length
  strbuilder --repeat/-r <num>		prints str of NUM repetitions
  strbuilder --seperator/-s <sep_char>	seperate str elements
  strbuilder --terminate/-t <end_char>	close string with this character
     SPECIAL for -s/-t: nl = $'\n'	tab = $'\t'
  UNFLAGGED ARGS added to <str_elements> UNLESS num is currently 0"
exit 0; fi

resetpress () {
	num=0; stamp=''; seperator=''; terminator=''
	repeatflag=false; numberflag=true
}

printingpress () {
	message=''
	if [ "$repeatflag" = "true" ]; then
		length=$(($num-1))
	elif [ "$numberflag" = "true" ]; then
		length="$(( $num / ${#stamp} ))"
	fi

	#echo "stamp:$stamp;sep:${seperator@Q};length:$length"

	count=0
	for index in $(seq 0 "$length"); do
		message+="$stamp$seperator"
		count=$((count+1))
	done
	if [ "$numberflag" = true ]; then
		remainder="$(($num % ($count * ${#stamp})))"
		message+="${stamp:$remainder}$separator"
		printf "%s" "${message:0:$remainder}$terminator"
	elif [ "$repeatflag" = "true" ]; then
		printf "%s" "$message$terminator"
	fi
}

resetpress

while [ "$#" -gt 0 ]; do
	if [ "$1" = "-r" ] || [ "$1" = "--repeat" ]; then #echo "rflag"
		repeatflag="true"; numberflag="false"; 
		shift; continue; fi
	if [ "$1" = "-n" ] || [ "$1" = "--number" ]; then #echo "nflag"
		numberflag="true"; repeatflag="false"
		shift; continue; fi
	if [ "$1" = "-s" ] || [ "$1" = "--seperator" ]; then #echo "sflag"
		if [ "$2" = "nl" ]; then seperator+=$'\n'
		elif [ "$2" = "tab" ]; then	seperator+=$'\t'
		else seperator+="$2"; fi
		shift 2; continue
	fi
	if [ "$1" = "-t" ] || [ "$1" = "--terminator" ]; then
		if [ "$2" = "nl" ]; then terminator+=$'\n'
		elif [ "$2" = "tab" ]; then	terminator+=$'\t'
		else terminator+="$2"; fi
		shift 2; continue
	fi
	#Allows for multiple calls within same command
	if [ "$1" = "--" ]; then printingpress; resetpress; shift; continue; fi
	if [ "$1" = "--dash" ]; then echo "moved to ~/bin/strbuilts"; exit 0; fi
	#if no flags caught
	if [ "$num" -eq 0 ] && [ "${1//[0-9]/}" = '' ]; then 
		num="$1"; shift; continue; fi
	#detect if brace expansion incoming
	stamp+="$1"; shift
done
# dont make none of something
if [ "$num" -lt 1 ] || [ "$stamp" = '' ]; then printf ''; exit 0; fi
printingpress

exit 0
